[project]
name = "io.github.swyddfa.Wneud"
version = "0.1.0"
authors = [{name = "Alex Carney", email = "alcarneyme@gmail.com"}]
maintainers = [{name = "Alex Carney", email = "alcarneyme@gmail.com"}]
description = "Automations and workflows for your Desktop"
license = "GPL-3.0-or-later"
requires-python = ">=3.13"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: End Users/Desktop",
    "Topic :: Utilities",
    "Programming Language :: Python",
    "Operating System :: POSIX :: Linux",
]
readme = "README.md"
dependencies = [
    "PyQt6",
    # This is a required dependency, but I have issues trying to install this from PyPi.
    # Currently relying on flatpak to ensure it is available.
    #
    # "systemd-python",
    "varlink",
]

[project.scripts]
wneud = "wneud.app:main"

[dependency-groups]
dev = [
  "requirements-parser",
  "pytest"
]

[tool.pyright]
include = ["src"]
exclude = ["build", ".flatpak-builder", "dist"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.data-files]
"share/applications" = ["io.github.swyddfa.Wneud.desktop"]
"share/icons/hicolor/scalable/apps" = ["io.github.swyddfa.Wneud.svg"]
"share/metainfo" = ["io.github.swyddfa.Wneud.metainfo.xml"]
